New common build files

diff --git a/coreutils/build-functions b/coreutils/build-functions
--- a/coreutils/build-functions
+++ b/coreutils/build-functions
@@ -6,10 +6,13 @@
 # definitions have been sourced
 #
 export TOP=$(pwd)
-export OBJ=$TOP/obj/
-export SRC=$TOP/src/
-
+export OBJ=$TOP/obj
+export SRC=$TOP/src
+export LOG=$TOP/log
 ARGS=$@
+NAME=$(basename $0)
+
+set -o pipefail
 
 #
 # check_source_dir <source-name>
@@ -44,14 +47,14 @@ check_source_dir()
 #
 # change_into_obj_directory 
 #
-# Create and change into the directory $OBJ$LIB_NAME
+# Create and change into the directory $OBJ/$LIB_NAME
 # where the project will be built.
 #
 change_into_obj_directory()
 {
         cd $TOP
-        mkdir -p $OBJ$LIB_NAME
-	cd $OBJ$LIB_NAME
+        mkdir -p $OBJ/$LIB_NAME
+	cd $OBJ/$LIB_NAME
 	if [ $? -ne 0 ]; then
 	   echo
 	   echo Can\'t change to $OBJ/$LIB_NAME directory
@@ -68,12 +71,31 @@ change_into_obj_directory()
 #
 configure_it()
 {
-	$SRC/$LIB_NAME/configure "$@"
+
+	# Make sure the cross compilation suite
+	# is in place before starting this stage
+
+	if ! type $CC > /dev/null ; then
+	    echo
+	    echo "ERROR : Unable to find $CROSS_COMPILE toolchain"
+	    echo "Check CROSS_COMPILE and CROSS are set correctly"
+	    echo "in the build-common script"
+	    echo
+	    echo Exiting \($SECONDS seconds\)
+            exit -1
+	fi
+
+        mkdir -p $LOG
+	$SRC/$LIB_NAME/configure "$@" |& tee $LOG/"$NAME"_configure.log
 	if [ $? -ne 0 ]; then
     	   echo   
-           echo configure for $LIB_NAME failed. Exiting
+           echo configure for $LIB_NAME failed. See $LOG/"$NAME"_configure.log
+	   echo and config.log under $(pwd)
+	   echo Exiting \($SECONDS seconds\)
 	   exit -1
-	fi	
+	fi
+	echo configure for $LIB_NAME complete. See $LOG/"$NAME"_configure.log
+	echo and config.log under $(pwd)
 }
 #
 # make_it [make-params]
@@ -85,12 +107,15 @@ configure_it()
 #
 make_it()
 {
-	make -j$J $@ $ARGS
+        mkdir -p $LOG	
+	make -j$J $@ $ARGS |& tee $LOG/"$NAME"_make.log
 	if [ $? -ne 0 ]; then
     	   echo
-           echo make for $LIB_NAME failed. Exiting
+           echo make for $LIB_NAME failed. See $LOG/"$NAME"_make.log
+	   echo Exiting \($SECONDS seconds\)
 	   exit -1
-	fi	
+	fi
+	echo make for $LIB_NAME complete. See $LOG/"$NAME"_make.log
 }
 
 #
@@ -101,12 +126,16 @@ make_it()
 #
 install_it()
 {
-	make DESTDIR=$BUILDHOST_DEST install
+        mkdir -p $LOG
+	make DESTDIR=$BUILDHOST_DEST install |& tee $LOG/"$NAME"_install.log
 	if [ $? -ne 0 ]; then
     	   echo   
-           echo make install of $LIB_NAME to $BUILDHOST_DEST Failed. Exiting
+           echo make install of $LIB_NAME to $BUILDHOST_DEST Failed.
+	   echo See $LOG/"$NAME"_install.log
+	   echo Exiting \($SECONDS seconds\)
 	   exit -1
-	fi	
+	fi
+	echo make install for $LIB_NAME complete. See $LOG/"$NAME"_install.log	
 }
 
 #
@@ -120,7 +149,7 @@ finish_it()
         echo
 	echo "****************************************"
 	echo 
-	echo "Success! Finished installing $LIB_NAME to $BUILDHOST_DEST ($SECONDS seconds)"
+	echo Success! $NAME finished installing $LIB_NAME to $BUILDHOST_DEST \($SECONDS seconds\)
 	echo
 	echo "****************************************"
 	echo
